/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/skel.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {/* highlight-line */
      actions['Armature|mixamo.com|Layer0'].play(); /* highlight-line */
   }); 
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        
        <group name="Camera" position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <group name="Armature" rotation={[Math.PI / 1.2, 0, 0]} scale={0.0008}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Skeleton" geometry={nodes.Skeleton.geometry} material={materials['Material.001']} skeleton={nodes.Skeleton.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/skel.glb')
