/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/css.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.CSS.geometry} material={materials['CSS.002']} position={[-0.05, 0.86, -0.11]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/css.glb')
