/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/html.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.HTML.geometry} material={materials.HTML} position={[-0.04, 0.68, 0.11]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/html.glb')
