/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  useFrame(({ clock }) => {
    group.current.rotation.y = clock.getElapsedTime() * 1.5;
  });
  const { nodes, materials } = useGLTF('/html.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.HTML.geometry} material={materials.HTML} position={[0,0,0]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/html.glb')
