/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model({ ...props }) {
  const group = useRef();
  useFrame(({ clock }) => {
    group.current.rotation.y = Math.sin(clock.getElapsedTime());
  });
  const { nodes, materials } = useGLTF("/javascript.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.JAVASCRIPT.geometry}
        material={materials["JAVASCRIPT.001"]}
        position={[-0.5, 1, 0.5]}
        
        rotation={[0, 100, 0]}
        scale={0.05}
      />
    </group>
  );
}

useGLTF.preload("/javascript.glb");
